theme: jekyll-theme-minima
title: TRACE Questionnaire
description: Part of the TRACE project, this questionnaire explores how students emotionally connect with their cities. By marking meaningful places and answering brief questions, you’ll help build an emotional map that fosters cultural understanding and inclusion across the Arqus Alliance.
